### ISSUE TITLE
Cannot construct function_ref from function taking std::function as argument

### ISSUE THREAD

**Issue by no-more-secrets** [TartanLlama/function_ref#14]
Here is a simple reproducer that is giving me a compiler error on the latest clang:

```C++
using FuncGood = tl::function_ref<void(int, int)>;
FuncGood good = []( int, int ){}; // ok

using FuncBad = tl::function_ref<void(int, std::function<void()>)>;
FuncBad bad = []( int, std::function<void()> ){}; // compile error
```

In particular, the error message says that the desired constructor is not viable because the condition `detail::is_invocable_r` is not holding true, so I'm thinking there might be an issue with your implementation of `is_invocable_r`?

Relevant part of error message (I believe):
```
function_ref/function_ref.hpp:144:15: note: candidate constructor not viable: no known conversion from '(lambda at main.cpp:121:19)' to 'const function_ref<void (int, std::__1::function<void ()>)> &' for 1st argument function_ref/function_ref.hpp:153:32: note: candidate template ignored: requirement 'detail::is_invocable_r_impl<std::__1::integral_constant<bool, true>, void, (lambda at main.cpp:121:19) &&, int, std::__1::function<void ()> >::value' was not satisfied [with F = (lambda at main.cpp:121:19)]
```

**Comment by TartanLlama** [comment]
I can't reproduce this: https://godbolt.org/z/HY3EH2
Can you post exact version of Clang and compiler flags, or ideally a Compiler Explorer link?

**Comment by no-more-secrets** [comment]
Ok I updated my version of function_ref and the issue went away, so must have been fixed since I cloned my copy in late June 2019.  Thanks
