### ISSUE TITLE
Warning with GCC

### ISSUE THREAD

**Issue by mortenvp** [TartanLlama/function_ref#4]
Hi @TartanLlama ,
We are also seeing a warning with g++:

```
In file included from ../../resolve_symlinks/function_ref-source/tests/call.cpp:2:
../../resolve_symlinks/function_ref-source/function_ref.hpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
../../resolve_symlinks/function_ref-source/function_ref.hpp:93:29: warning: ‘<anonymous>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return std::forward<Fn>(f)(std::forward<Args>(args)...);
          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Seems to be triggered by this test:

```
    {
        int i = 0;
        tl::function_ref<void()> fr = [&i]{ i = 42; };
        fr();
        REQUIRE(i == 42);
    }
``` 
However, I'm not really sure how to fix it. The warning is triggered by g++ 8.2.0.

**Comment by TartanLlama** [comment]
Hmm, I can't seem to replicate this: https://godbolt.org/z/aCDuYb
What compiler flags are you using?

**Comment by mortenvp** [comment]
I also cannot reproduce.. that is strange (https://godbolt.org/z/lk6s12). 

I will close this issue and re-open if I find a way to reproduce it.

**Comment by mortenvp** [comment]
Hi @TartanLlama seems #5 also fixed this issue :+1:
