### ISSUE TITLE
Should `Apple()` be convertible to `tl::function_ref<Fruit()>`?

### ISSUE THREAD

**Issue by Quuxplusone** [TartanLlama/function_ref#9]
https://godbolt.org/z/2r5aEI
```
struct Fruit {};
struct Apple : Fruit {};

Apple *getApple() { return nullptr; }

static_assert(std::is_invocable_r_v<Fruit*, decltype(getApple)>);

tl::function_ref<Fruit*()> bar()
{
    return getApple;  // ERROR: no such conversion
}
```

`std::function` permits implicit conversion from `Apple*()` to `std::function<Fruit*()>`, and from `Apple()` to `std::function<Fruit()>`, and I think these makes sense to support. (Similarly, from `long()` to `std::function<int()>`; I'm somehow less thrilled by that one, philosophically speaking.)

I believe the wording of @SuperV1234's [P0792](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0792r3.html) supports such conversions, and intentionally so.

However, ulterior motive alert — watch out! — you might have to pick and defend a behavior for

    Apple *getApple();
    Apple *getRottenApple();
    int main() {
        tl::function_ref<Apple*()> a = getApple;
        tl::function_ref<Apple*()> b = a;
        tl::function_ref<Fruit*()> c = a;
        a = getRottenApple;
        Fruit *rb = b();  // does this result in a call to getApple, or getRottenApple? why?
        Fruit *rc = c();  // does this result in a call to getApple, or getRottenApple? why?
    }

**Comment by TartanLlama** [comment]
Fixed in https://github.com/TartanLlama/function_ref/commit/3cdadfaa0fa95ec10f17e1847249852e6dbac85c.

On the second point, eugh, that's super icky. Has this been raised against the proposal? Seems like it'd need a converting copy constructor for both to call `getApple`.

**Comment by Quuxplusone** [comment]
> On the second point, eugh, that's super icky. Has this been raised against the proposal?

I have not raised this issue in any way other than mentioning it here (and with that ping at @SuperV1234). I do think it would be nice for the proposal to mention it and include an example in the proposed wording.

> Seems like it'd need a converting copy constructor for both to call `getApple`.

Yes. I'm fairly confident that `b()` *must* call `getApple`, although I am having trouble coming up with a 100% realistic piece of code that would break if we made `b` simply refer-to `a`. (Code involving `std::future<tl::function_ref<Apple*()>>` is not realistic IMHO.)

I'm ambivalent on `c()` — maybe it's okay for it to call `getRottenApple`. However, I suspect that as soon as someone finds a piece of code that is broken by `b`-merely-referring-to-`a`, we'll be able to make a very small tweak to it that also looks 100% realistic and yet is broken by `c`-merely-referring-to-`a`.

**Comment by vittorioromeo** [comment]
Interesting. My intuition tells me that:

```cpp
tl::function_ref<Apple*()> a = getApple;
tl::function_ref<Apple*()> b = a;
a = getRottenApple;
a(); // calls getRottenApple
b(); // calls getApple
```

I'm confident that the paper agrees as the trivial copy-constructor mentions:

> Effects: constructs a function_ref referring to the same callable rhs refers to.

This implies that `b` does not refer to `a`, but refers to whatever `a` was referring to at the time of copy-construction.

---

This is also my intuition for the second case:

```cpp
tl::function_ref<Apple*()> a = getApple;
tl::function_ref<Fruit*()> c = a;
a = getRottenApple;
a(); // calls getRottenApple
c(); // calls getRottenApple
```

Since the types of `a` and `c` are different, this is not copy-construction. `c` refers directly to `a`. The paper seems to agree on this as well. I honestly don't think this will be a problem in practice (as I have never encountered this case), but I'm open to further discussion.

**Comment by Quuxplusone** [comment]
I guess the further discussion would be to point out that "not a copy constructor" also applies to slicing constructors, e.g. if I have
```
struct A : std::function_ref<int()> { using function_ref::function_ref; };
```
then assigning or converting an `A` to a `function_ref` will have reference, not value, semantics. Example: https://wandbox.org/permlink/6NkgZ5eAy1JbeJoc

Still probably the right choice, philosophically speaking, but still certainly worth calling out in an example in the formal wording so that implementors and programmers will be on the same page.
